services:
    mysql:
        container_name: mysql-pictura
        image: mysql:latest
        environment:
            MYSQL_USER: username
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: pictura
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - spring-demo
        restart: unless-stopped

    mail-dev:
        container_name: mail-dev-pictura
        image: maildev/maildev
        ports:
            - 1080:1080
            - 1025:1025

networks:
    spring-demo:
        driver: bridge

volumes:
    mysql-data:
        driver: local
