spring:
    datasource:
        url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC&useSSL=true&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Root@1234
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        database: mysql
    mail:
        host: localhost
        port: 1025
        username: badusha
        password: badusha
        properties:
            mail:
                smtp:
                    trust: "*"
                auth: true
                starttls:
                    enable: true
                connectiontimeout: 5000
                timeout: 3000
                writetimeout: 5000


admin:
    email: admin@example.com
    password: admin
security:
    jwt:
        expiration-time: 86400000
        secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
mailing:
    frontend:
        activation-url: http://localhost:4200/activate-account
server:
    port: 1200
    shutdown: graceful